### PR TITLE
Update Travis CI config

### PR DESCRIPTION
**Pull request by mbrukman**
Given this config, we can enable Travis CI to address https://github.com/OpenTSDB/asyncbigtable/issues/17

### CODE REVIEW

**Comment by mbrukman** [comment]
@csoulios – I rebased my branch on top of the [`.travis.yml` you submitted earlier](https://github.com/OpenTSDB/asyncbigtable/commit/3fdff4ea7b716e0ddbab50173028222931c5a8e8), and added a few more settings to use containers and a newer version of Linux distro. Please take a look.

**Comment by csoulios** [comment]
Thanks so much for taking care of this @mbrukman

**Comment by mbrukman** [comment]
@csoulios – sorry, that was not ready to merge yet, I was waiting for the Travis results before declaring victory, and as you can see, all my attempts at fixing this still failed (there' a red `x` next to every one of my commits that was tested individually by Travis).

Any thoughts on what to try next?

**Comment by csoulios** [comment]
It seems that maven still runs out of memory and we are receiving the following error:
[ERROR] GC overhead limit exceeded -> [Help 1]

In my local environment the project is built without problems. I suppose in yours too. I will increase the MAVEN heap to 4g (although it should not require so much memory) and check again

**Pull request merged**
