### PR TITLE
Added column prefix filter and key only filter

### PR DESCRIPTION
**Pull request by overthetop**
I've added support for two "new" filters. I'm using the asyncbigtable driver outside opentsdb and my project relies on those filters.

### CODE REVIEW

**Review by sduskis — CHANGES_REQUESTED** [review]
Can you please add the standard Copyright headers?
Also, please add some basic unit tests to make sure that the HBase filters are built as expected.

**Comment by sduskis** [comment]
As a meta commentary, have you considered using Bigtable's HBase 2 async libraries?  They are more robust than AsyncBigtable's implementation.

**Comment by overthetop** [comment]
Yes, sorry about that. Regarding the hbase2 async libraries, they look nice but I have a lot of code using the hbase asynchbase lib. In future development I'll definitely use the bigtable async driver.

**Comment by overthetop** [comment]
@sduskis is there something else that I've missed?

**Review by sduskis — APPROVED** [review]

**Pull request merged**
